"""empty message

Revision ID: 869e66cd6be3
Revises: 
Create Date: 2018-06-13 12:42:35.790575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = '869e66cd6be3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=255), nullable=True),
    sa.Column('current_login_ip', sa.String(length=255), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rolesandusers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], )
    )
    # op.drop_index('sys_c007269', table_name='USER')
    # op.drop_index('sys_c007270', table_name='USER')
    # op.drop_table('USER')
    # op.drop_table('roles_users')
    # op.drop_index('sys_c007262', table_name='role')
    # op.drop_table('role')
    op.execute('create sequence id start with 1 increment by 1 nocache nocycle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_role'),
    oracle_resolve_synonyms=False
    )
    op.create_index('sys_c007262', 'role', ['name'], unique=True)
    op.create_table('roles_users',
    sa.Column('user_id', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    sa.Column('role_id', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='fk_roles_users__role_id'),
    sa.ForeignKeyConstraint(['user_id'], ['USER.id'], name='fk_roles_users__user_id'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='pk_roles_users')
    )
    op.create_table('USER',
    sa.Column('id', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=False),
    sa.Column('username', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('email', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('password', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('active', oracle.NUMBER(precision=1, scale=0, asdecimal=False), nullable=True),
    sa.Column('confirmed_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('current_login_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('login_count', oracle.NUMBER(precision=10, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user')
    )
    op.create_index('sys_c007270', 'USER', ['email'], unique=True)
    op.create_index('sys_c007269', 'USER', ['username'], unique=True)
    op.drop_table('rolesandusers')
    op.drop_table('auth_user')
    op.drop_table('auth_role')
    # ### end Alembic commands ###
