# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-06-15 10:10
from __future__ import unicode_literals

import datetime
from pony import orm

dependencies = []

def define_entities(db):
    class Department(db.Entity):
        number = orm.PrimaryKey(int, auto=True)
        name = orm.Required(str, unique=True)
        groups = orm.Set('Group')
        courses = orm.Set('Course')

    class Group(db.Entity):
        number = orm.PrimaryKey(int)
        major = orm.Required(str)
        dept = orm.Required('Department')
        students = orm.Set('Student')

    class Course(db.Entity):
        name = orm.Required(str)
        semester = orm.Required(int)
        lect_hours = orm.Required(int)
        lab_hours = orm.Required(int)
        credits = orm.Required(int)
        dept = orm.Required(db.Department)
        students = orm.Set('Student')
        professor = orm.Required('Professor')
        orm.PrimaryKey(name, semester)

    class Person(db.Entity):
        name = orm.Required(str)
        tel = orm.Optional(str)
        picture = orm.Optional(bytes, lazy=True)

    class Student(db.Entity):
        name = orm.Required(str)
        tel = orm.Optional(str)
        picture = orm.Optional(bytes, lazy=True)
        dob = orm.Required(datetime.date)
        gpa = orm.Required(float)
        mentor = orm.Optional('Professor')
        group = orm.Required('Group')
        courses = orm.Set('Course')

    class Professor(db.Person):
        degree = orm.Required(str)
        students = orm.Set('Student')
        courses = orm.Set('Course')
