# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-06-08 15:44
from __future__ import unicode_literals

import datetime
from pony import orm
from pony.migrate import diagram_ops as op

dependencies = ['0001_initial']

operations = [
    op.AddEntity('Base', ['Entity'], [('created_on', orm.Required(datetime.datetime)), ('id', orm.PrimaryKey(int, auto=True)), ('updated_on', orm.Optional(datetime.datetime))]),
    op.AddEntity('User', ['Entity'], [('active', orm.Optional(bool)), ('confirmed_at', orm.Optional(datetime.datetime, sql_default='CURRENT_TIMESTAMP')), ('current_login_at', orm.Optional(datetime.datetime, sql_default='CURRENT_TIMESTAMP')), ('email_address', orm.Required(str, column='email', unique=True)), ('first_name', orm.Optional(str)), ('id', orm.PrimaryKey(int, auto=True)), ('last_login_at', orm.Optional(datetime.datetime, sql_default='CURRENT_TIMESTAMP')), ('last_name', orm.Optional(str)), ('login_count', orm.Optional(int)), ('password', orm.Required(str)), ('username', orm.Required(str, unique=True))]),
    op.AddEntity('Role', ['Entity'], [('description', orm.Optional(str)), ('id', orm.PrimaryKey(int, auto=True)), ('name', orm.Required(str, unique=True))]),
    op.AddAttr('StoredItem', 'test', orm.Optional(str, sql_default="''")),
    op.AddRelation('User', 'roles', orm.Set('Role', column='role_id', table='roles_users'), 'users', orm.Set('User', column='user_id'))]
