# -*- coding: utf-8 -*-
# Generated by Pony ORM 0.8-dev on 2018-06-17 18:48
from __future__ import unicode_literals

from pony import orm
from pony.migrate import diagram_ops as op

dependencies = ['0001_initial']

operations = [
    # op.RemoveEntity('Person')
    # op.AddAttr('Professor', 'id', orm.PrimaryKey(int, auto=True)),
    # op.AddAttr('Professor', 'name', orm.Required(str, initial='Null')),
    # op.AddAttr('Professor', 'tel', orm.Optional(str, sql_default="''"))
    ]

def define_entities(db):

    class Professor(db.Entity):
        name = orm.Required(str)
        tel = orm.Optional(str)
        picture = orm.Optional(bytes, lazy=True)
        degree = orm.Required(str)
        students = orm.Set('Student')
        courses = orm.Set('Course')
