"""empty message

Revision ID: 54dd231fa06f
Revises: 5de78ec2669a
Create Date: 2018-05-30 15:56:55.930722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54dd231fa06f'
down_revision = '5de78ec2669a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'first_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'first_name', nullable=True)
    
    # ### end Alembic commands ###
